scan_new:
    path: /scan/new
    methods: [ GET, POST ]
    controller: App\Controller\ScanController::new

scan_index:
    path: /scan/{page}
    methods: [ GET ]
    controller: App\Controller\ScanController::index
    defaults:
        page: 1